### ISSUE TITLE
AutoLayout Support

### ISSUE THREAD

**Issue by mstrchrstphr** [tolo/InterfaCSS#15]
@tolo Really fantastic work with this! 

I noticed AutoLayout support is something that hasn't been implemented yet. Just wanted to hear your thoughts on why you chose to go with absolution positioning over AutoLayout (not that it was a bad choice). Is AutoLayout a direction you think this may take in the future?

This also ties in a bit to supporting multiple devices... I imagine in order to support multiple devices (or orientations) we'll either have to a) write additional layout code or b) create a separate CSS file. Usually different orientations have different layouts anyways so a separate file may not be a bad thing.

**Comment by tolo** [comment]
Just an update related to this issue: As of 1.0,  there is now support for a more advanced layout system, that does many of the things that Auto Layout can do, but in a way more in line with the philosophy of InterfaCSS. And although I haven't completely ruled out adding some form of support for Auto Layout in the future, the likelihood of that happening has perhaps somewhat decreased, which is why I'm closing this issue for now. 

Also, an update regarding the second bit of this issue: there is now support for using device type, interface orientation and size class as pseudo classes (multiple pseudo classes can be chained) in style declarations.

Cheers, 
Tobias
